version: "3.9"
services:
  web:
    # 同じディレクトリにあるdockerFileを参照
    build: .
    # Railsのサーバーを起動している
    # 立ち上げる毎にserver.pidのファイルを削除(エラー回避用)
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
volumes:
  postgresql-data:
    driver: local
