FROM ruby:3.1.4

WORKDIR /app

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

COPY Gemfile Gemfile.lock ./

RUN bundle install

EXPOSE 4000

CMD ["rails", "server", "-b", "0.0.0.0"]