default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: janhu_api_development

test:
  <<: *default
  database: janhu_api_test

production:
  <<: *default
  database: janhu_api_production
  username: janhu_api
  password: <%= ENV['janhu_api_DATABASE_PASSWORD'] %>
